# docker-compose.yml
version: "3.9"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: chatuser
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: chatdb
    ports:
      - "5432:5432"  # Exposes Postgres if you want to connect from outside

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://chatuser:secretpassword@db:5432/chatdb
      LLM_API_URL: ${LLM_API_URL:-http://host.docker.internal:1234/v1/chat/completions}
      LLM_MODEL: ${LLM_MODEL:-google/gemma-3-12b}
